[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
cbor = false
gas_reports = ["*"]
gas_reports_ignore = []

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false

[rpc_endpoints]
base = "https://mainnet.base.org"
base_testnet = "https://goerli.base.org"
arbitrum = "https://arb1.arbitrum.io/rpc"
arbitrum_testnet = "https://goerli-rollup.arbitrum.io/rpc"
local = "http://localhost:8545"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
number_underscore = "thousands" 